### ISSUE TITLE
The container lacks a dispose function

### ISSUE THREAD

**Issue by jorgensigvardsson** [westermo/FactoryGenerator#3]
Many DI containers ensures that objects allocated by the container are disposed when the DI container itself is disposed. It would be a great feature to have!

**Comment by carl-andersson-at-westermo** [comment]
Sounds like a good idea. 
Though I suppose it only makes sense for the "Singleton"-style objects generated by container, since those are the only ones it itself keeps track of (The non-singleton objects created the container does not save a reference to, at this time, adding 'auto-disposability' for them would force the container to track them, which might cause them to outlive their intended usefulness)

**Comment by jorgensigvardsson** [comment]
I _think_ Autofac and others may track transient objects, but on the other hand, those keep track of life time scopes. The main use case for such containers are in ASP.NET applications and the like, where there's a new life time scope for each request. Transient objects don't live that long I think, so there's not many objects to track.

I think to support ASP.NET kind of applications, then both scopes and transient object tracking are needed, but that's a different user story in my mind...
